name: Client CI

on:
  pull_request:
    branches: [ main, master, dev ]

jobs:
  check-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check TypeScript types
        run: npx tsc --noEmit

      - name: Run linter
        run: npm run lint
